CREATE TABLE Sheet1(Column_1 VARCHAR(10),Column_2 VARCHAR(10),Column_3 VARCHAR(10),Column_4 VARCHAR(10),Column_5 VARCHAR(10),Column_6 VARCHAR(10),Column_7 VARCHAR(10));
INSERT INTO Sheet1 (Column_1,Column_2,Column_3,Column_4,Column_5,Column_6,Column_7) VALUES 
('-- SQL-скрипт оформлен на диалекте PostgreSQL.','','','','','',''),
('-- 1. Вывести марку и модель автомобиля',' у которого самая высокая цена по','','','','',''),
('-- всей базе','','','','','',''),
('CREATE TABLE Autos (brand VARCHAR(100)',' model VARCHAR(100)',' price INTEGER);','','','',''),
('		INSERT INTO autos (brand',' model',' price) VALUES ('BMW'',' 'X6'',' 13000000);','',''),
('		INSERT INTO autos (brand',' model',' price) VALUES ('KIA'',' 'Optima'',' 5000000);','',''),
('		INSERT INTO autos (brand',' model',' price) VALUES ('BMW'',' 'X5'',' 9000000);','',''),
('        	INSERT INTO autos (brand',' model',' price) VALUES ('Nissan'',' 'Almera'',' 3000000);','',''),
('        ','','','','','',''),
('SELECT brand',' model','','','','',''),
('  FROM Autos','','','','','',''),
('  WHERE price IN (SELECT MAX(price) ','','','','','',''),
('                    FROM Autos);','','','','','',''),
('-- 2. Вывести на против фамилии каждого сотрудника название организации','','','','','',''),
('CREATE TABLE Employee (id integer',' Surename varchar(100));','','','','',''),
('		INSERT INTO Employee (id',' Surename) VALUES (1',' 'Иванов');','','','',''),
('		INSERT INTO Employee (id',' Surename) VALUES (2',' 'Петров');','','','',''),
('        	INSERT INTO Employee (id',' Surename) VALUES (3',' 'Сидоров');','','','',''),
('        ','','','','','',''),
('CREATE TABLE EmployeePosition (employeeid INTEGER',' ','','','','',''),
('                               positionid INTEGER',' ','','','','',''),
('                               startDate DATE NOT NULL','','','','','',''),
('                               endDate DATE NOT NULL','','','','','',''),
('                               Companyid INTEGER);','','','','','',''),
('		INSERT INTO EmployeePosition (employeeid',' positionid',' startDate',' endDate',' Companyid) ','',''),
('        			VALUES (1',' 10',' '2016-01-01'',' '2016-04-01'',' 100);','',''),
('		INSERT INTO EmployeePosition (employeeid',' positionid',' startDate',' endDate',' Companyid) ','',''),
('        			VALUES (1',' 13',' '2016-04-02'',' '5999-12-31'',' 100);','',''),
('        	INSERT INTO EmployeePosition (employeeid',' positionid',' startDate',' endDate',' Companyid) ','',''),
('        			VALUES (2',' 11',' '2016-02-02'',' '5999-12-31'',' 101);','',''),
('        	INSERT INTO EmployeePosition (employeeid',' positionid',' startDate',' endDate',' Companyid) ','',''),
('        			VALUES (3',' 12',' '2016-03-02'',' '5999-12-31'',' 100);','',''),
('CREATE TABLE Company (id INTEGER',' companyName VARCHAR(100));','','','','',''),
('		INSERT INTO Company (id',' companyName) VALUES (100',' 'Альфа-Банк');','','','',''),
('		INSERT INTO Company (id',' companyName) VALUES (101',' 'Эра IT');','','','',''),
('WITH EmployeeCompany AS (','','','','','',''),
('  SELECT DISTINCT Surename',' Companyid ','','','','',''),
('  FROM Employee e INNER JOIN EmployeePosition ep','','','','','',''),
('       ON e.id = ep.employeeid','','','','','',''),
('  )','','','','','',''),
('  ','','','','','',''),
('SELECT Surename',' companyName ','','','','',''),
('  FROM EmployeeCompany ec INNER JOIN Company c','','','','','',''),
('    ON ec.companyid = c.id;','','','','','',''),
('-- 3. Написать запрос',' который выведет сумму задолженности по','','','','',''),
('-- кредитным требованиям в разрезе отчетных дат и продуктов','','','','','',''),
('CREATE TABLE DEALS (report_date DATE NOT NULL',' deal_id VARCHAR(100)',' debt FLOAT);','','','',''),
('		INSERT INTO DEALS (report_date',' deal_id',' debt) ','','','',''),
('        			VALUES ('2021-06-30'',' 'ACCPS1234512345'',' 324542.02);','','','',''),
('                    ','','','','','',''),
('CREATE TABLE PRODUCTS (deal_id VARCHAR(100)',' product VARCHAR(100));','','','','',''),
('		INSERT INTO PRODUCTS (deal_id',' product) ','','','','',''),
('        			VALUES ('ACCPS1234512345'',' 'Mortgage');','','','','',''),
('                    ','','','','','',''),
('SELECT report_date','','','','','',''),
('       product','','','','','',''),
('       SUM(debt) AS debt_sum','','','','','',''),
('  FROM DEALS d INNER JOIN PRODUCTS p','','','','','',''),
('    ON d.deal_id = p.deal_id','','','','','',''),
('  GROUP BY report_date',' product;','','','','',''),
('-- 4. Необходимо написать следующие запросы:','','','','','',''),
('--		a. Запрос',' который выведет все договоры (уникальный список)',' у','','','',''),
('--		которых код события = 2 встречается более 1 раза;','','','','','',''),
('--		b. Запрос',' который выведет два значения: количество уникальных','','','','',''),
('--		договоров',' у которых есть действующее событие на отчетную дату',' и','','','',''),
('--		количество договоров',' по которым все события завершены;','','','','',''),
('CREATE TABLE DEFAULTS (deal_id INTEGER',' ','','','','',''),
('                       event_code INTEGER',' ','','','','',''),
('                       event_start_date DATE NOT NULL','','','','','',''),
('                       event_end_date DATE','','','','','',''),
('                       product VARCHAR(100));','','','','','',''),
('		INSERT INTO DEFAULTS (deal_id',' event_code',' event_start_date',' event_end_date',' product) ','',''),
('        			VALUES (1234',' 1',' (TO_DATE('01.01.2018'',' 'DD.MM.YYYY'))',' (TO_DATE('15.12.2018'',' 'DD.MM.YYYY'))',' 'Mortgage');'),
('		INSERT INTO DEFAULTS (deal_id',' event_code',' event_start_date',' event_end_date',' product) ','',''),
('        			VALUES (1234',' 4',' (TO_DATE('17.12.2018'',' 'DD.MM.YYYY'))',' (TO_DATE('16.04.2019'',' 'DD.MM.YYYY'))',' 'Mortgage');'),
('		INSERT INTO DEFAULTS (deal_id',' event_code',' event_start_date',' event_end_date',' product) ','',''),
('        			VALUES (1234',' 2',' (TO_DATE('21.05.2019'',' 'DD.MM.YYYY'))',' (TO_DATE('07.12.2019'',' 'DD.MM.YYYY'))',' 'Mortgage');'),
('		INSERT INTO DEFAULTS (deal_id',' event_code',' event_start_date',' event_end_date',' product) ','',''),
('        			VALUES (1234',' 4',' (TO_DATE('01.10.2020'',' 'DD.MM.YYYY'))',' (TO_DATE('28.02.2021'',' 'DD.MM.YYYY'))',' 'Mortgage');'),
('		INSERT INTO DEFAULTS (deal_id',' event_code',' event_start_date',' event_end_date',' product) ','',''),
('        			VALUES (1234',' 5',' (TO_DATE('30.09.2021'',' 'DD.MM.YYYY'))',' NULL',' 'Mortgage');',''),
('		INSERT INTO DEFAULTS (deal_id',' event_code',' event_start_date',' event_end_date',' product) ','',''),
('        			VALUES (5678',' 10',' (TO_DATE('15.08.2020'',' 'DD.MM.YYYY'))',' (TO_DATE('11.02.2021'',' 'DD.MM.YYYY'))',' 'Credit card');'),
('  		INSERT INTO DEFAULTS (deal_id',' event_code',' event_start_date',' event_end_date',' product) ','',''),
('        			VALUES (5678',' 1',' (TO_DATE('01.06.2021'',' 'DD.MM.YYYY'))',' (TO_DATE('30.08.2021'',' 'DD.MM.YYYY'))',' 'Credit card');'),
('		INSERT INTO DEFAULTS (deal_id',' event_code',' event_start_date',' event_end_date',' product) ','',''),
('        			VALUES (1234',' 2',' (TO_DATE('22.06.2019'',' 'DD.MM.YYYY'))',' (TO_DATE('25.06.2019'',' 'DD.MM.YYYY'))',' 'Mortgage');'),
(' ','','','','','',''),
('-- 4.a:','','','','','',''),
('WITH code2 AS (','','','','','',''),
('  SELECT deal_id',' event_code ','','','','',''),
('    FROM DEFAULTS','','','','','',''),
('    WHERE event_code = 2','','','','','',''),
('    )','','','','','',''),
('    ','','','','','',''),
('SELECT DISTINCT deal_id','','','','','',''),
('  FROM code2','','','','','',''),
('  GROUP BY deal_id','','','','','',''),
('  HAVING COUNT(event_code) > 1;','','','','','',''),
('  ','','','','','',''),
('-- 4.b: ','','','','','',''),
('SELECT (SELECT COUNT(DISTINCT deal_id) FROM DEFAULTS','','','','','',''),
('          WHERE event_end_date IS NULL) AS active_event_count','','','','','',''),
('       COUNT(DISTINCT deal_id) AS no_active_event_count','','','','','',''),
('  FROM DEFAULTS','','','','','',''),
('  WHERE event_end_date IS NOT NULL;','','','','','',''),
('-- 5. Необходимо написать следующие запросы:','','','','','',''),
('--			c. Запрос',' который выведет все договоры (уникальный список)',' у','','','',''),
('--			которых на текущую отчетную дату открыто событие с кодом события','','','','','',''),
('--			= 5',' при этом в истории по договору возникал также код события = 2','','','','',''),
('--			(договор 1234 из примера);','','','','','',''),
('--			d. Запрос',' который выведет все договоры (уникальный список)',' у','','','',''),
('--			которых на текущую дату открыто (действует) событие 5',' при этом в','','','','',''),
('--			истории по договору возникало событие 1 и после него возникало','','','','','',''),
('--			событие 2.','','','','','',''),
('-- 5.c:','','','','','',''),
('SELECT DISTINCT deal_id','','','','','',''),
('  FROM DEFAULTS def1','','','','','',''),
('  WHERE event_code = 5 AND ','','','','','',''),
('        event_end_date IS NULL AND','','','','','',''),
('        EXISTS (SELECT * FROM DEFAULTS def2','','','','','',''),
('                  WHERE def2.deal_id = def1.deal_id AND ','','','','','',''),
('                        event_code = 2 AND ','','','','','',''),
('                        event_end_date < def1.event_start_date);','','','','','',''),
('-- 5.d:','','','','','',''),
('SELECT DISTINCT deal_id','','','','','',''),
('  FROM DEFAULTS def1','','','','','',''),
('  WHERE event_code = 5 AND','','','','','',''),
('        event_end_date IS NULL AND','','','','','',''),
('  EXISTS (SELECT * FROM DEFAULTS def2','','','','','',''),
('            WHERE def2.deal_id = def1.deal_id AND ','','','','','',''),
('                  event_code = 1 AND ','','','','','',''),
('                  event_end_date < def1.event_start_date) AND ','','','','','',''),
('  EXISTS (SELECT * FROM DEFAULTS def3','','','','','',''),
('            WHERE def3.deal_id = def1.deal_id AND ','','','','','',''),
('                  event_code = 2 AND ','','','','','',''),
('                  event_start_date > (SELECT MAX(event_end_date)','','','','','',''),
('        				FROM DEFAULTS def4','','','','','',''),
('        				WHERE def4.deal_id = def1.deal_id AND ','','','','','',''),
('					      event_code = 1));','','','','','',''),
('-- 6. Получить отчет о всех сотрудниках со статусами их трудовых отношений с','','','','','',''),
('-- компанией. Статус вывести в двух вариантах: «Работает» или «Покинул компанию»','','','','','',''),
('-- (с указанием даты увольнения).','','','','','',''),
('CREATE TABLE EMPLOYEE (employee_id VARCHAR(100)','','','','','',''),
('                       first_name VARCHAR(100)',' ','','','','',''),
('                       last_name VARCHAR(100)','','','','','',''),
('                       hire_date DATE','','','','','',''),
('                       job_id VARCHAR(100)','','','','','',''),
('                       salary INTEGER);','','','','','',''),
('		INSERT INTO EMPLOYEE (employee_id',' first_name',' last_name',' hire_date',' job_id',' salary) ',''),
('        			VALUES ('02154520IT'',' 'Петров'',' 'Иван'',' '2020-02-15'',' '012'',' 180000);',''),
('		INSERT INTO EMPLOYEE (employee_id',' first_name',' last_name',' hire_date',' job_id',' salary) ',''),
('        			VALUES ('6675123M'',' 'Сергиенко'',' 'Владислав'',' '2019-06-01'',' '001'',' 150000); ',''),
('                    ','','','','','',''),
('CREATE TABLE JOB_HISTORY (employee_id VARCHAR(100)','','','','','',''),
('                          start_date DATE',' ','','','','',''),
('                          end_date DATE',' ','','','','',''),
('                          job_id VARCHAR(100)','','','','','',''),
('                          department_id VARCHAR(100));','','','','','',''),
('		INSERT INTO JOB_HISTORY (employee_id',' start_date',' end_date',' job_id',' department_id)','',''),
('        			VALUES ('02154520IT'',' '2020-02-15'',' NULL',' '012'',' '1010');','',''),
('		INSERT INTO JOB_HISTORY (employee_id',' start_date',' end_date',' job_id',' department_id)','',''),
('        			VALUES ('6675123M'',' '2019-06-01'',' '2023-02-28'',' '001'',' '1013');           ','',''),
('WITH Stat AS (','','','','','',''),
('  SELECT employee_id','','','','','',''),
('         CASE WHEN end_date IS NOT NULL THEN','','','','','',''),
('                   CONCAT('Покинул компанию'',' ' '',' end_date)','','','',''),
('              ELSE 'Работает'','','','','','',''),
('         END AS Status','','','','','',''),
('  FROM JOB_HISTORY','','','','','',''),
('  )','','','','','',''),
('SELECT CONCAT(first_name',' ' '',' last_name) AS Employee','','','',''),
('       Status','','','','','',''),
('  FROM EMPLOYEE e INNER JOIN Stat s','','','','','',''),
('    ON e.employee_id = s.employee_id;','','','','','',''),
('-- 7. Требуется написать запрос для вывода данных по кредитным сделкам','','','','','',''),
('--    совершённым в 2022 году',' с указанием процентной ставки',' действующий на дату','','','',''),
('--    совершения сделки.','','','','','',''),
('CREATE TABLE INTEREST (date_start DATE',' date_end DATE',' rate FLOAT);','','','',''),
('		INSERT INTO INTEREST (date_start',' date_end',' rate) ','','','',''),
('        	  		VALUES ((TO_DATE('01.01.2022'',' 'DD.MM.YYYY'))',' (TO_DATE('06.01.2022'',' 'DD.MM.YYYY'))',' 0.09);','',''),
('		INSERT INTO INTEREST (date_start',' date_end',' rate) ','','','',''),
('        	  		VALUES ((TO_DATE('07.01.2022'',' 'DD.MM.YYYY'))',' (TO_DATE('01.02.2022'',' 'DD.MM.YYYY'))',' 0.10);','',''),
('		INSERT INTO INTEREST (date_start',' date_end',' rate) ','','','',''),
('        	  		VALUES ((TO_DATE('02.02.2022'',' 'DD.MM.YYYY'))',' (TO_DATE('03.04.2022'',' 'DD.MM.YYYY'))',' 0.08);        ','',''),
('		INSERT INTO INTEREST (date_start',' date_end',' rate) ','','','',''),
('        	  		VALUES ((TO_DATE('04.04.2022'',' 'DD.MM.YYYY'))',' (TO_DATE('31.12.5999'',' 'DD.MM.YYYY'))',' 0.085);  ','',''),
('                    ','','','','','',''),
('CREATE TABLE DEALS (deal_id INTEGER',' deal_start_date DATE);','','','','',''),
('		INSERT INTO DEALS (deal_id',' deal_start_date) ','','','','',''),
('        	  		VALUES (1',' (TO_DATE('02.01.2022'',' 'DD.MM.YYYY')));','','','',''),
('		INSERT INTO DEALS (deal_id',' deal_start_date) ','','','','',''),
('        	  		VALUES (2',' (TO_DATE('17.03.2022'',' 'DD.MM.YYYY')));','','','',''),
('		INSERT INTO DEALS (deal_id',' deal_start_date) ','','','','',''),
('        	  		VALUES (3',' (TO_DATE('25.01.2022'',' 'DD.MM.YYYY')));                    ','','','',''),
('		INSERT INTO DEALS (deal_id',' deal_start_date) ','','','','',''),
('        	  		VALUES (4',' (TO_DATE('04.04.2022'',' 'DD.MM.YYYY')));  ','','','',''),
(' ','','','','','',''),
('SELECT DEALS.deal_id AS deal_id_in_2022',' ','','','','',''),
('       deal_start_date','','','','','',''),
('       INTEREST.rate AS rate','','','','','',''),
('  FROM DEALS',' INTEREST','','','','',''),
('  WHERE (deal_start_date BETWEEN INTEREST.date_start AND ','','','','','',''),
('                                 INTEREST.date_end) AND','','','','','',''),
('        TO_CHAR(deal_start_date',' 'YYYY-MM-DD') LIKE '2022%'','','','','',''),
('  ORDER BY rate DESC;','','','','','',''),
('-- 8. Написать запрос',' учитывая',' что в ячейках A и B результирующей выборки указана сумма по полю VALUE','','','',''),
('--    исходной таблицы.','','','','','',''),
('  ','','','','','',''),
('CREATE TABLE Sample (name VARCHAR(100)',' parameter VARCHAR(100)',' value INTEGER);','','','',''),
('    INSERT INTO Sample (name',' parameter',' value) VALUES ('N1'',' 'A'',' 100);','',''),
('    INSERT INTO Sample (name',' parameter',' value) VALUES ('N1'',' 'A'',' 200);','',''),
('    INSERT INTO Sample (name',' parameter',' value) VALUES ('N1'',' 'B'',' 100);','',''),
('    INSERT INTO Sample (name',' parameter',' value) VALUES ('N2'',' 'A'',' 300); ','',''),
('    INSERT INTO Sample (name',' parameter',' value) VALUES ('N2'',' 'B'',' 100);  ','',''),
('    INSERT INTO Sample (name',' parameter',' value) VALUES ('N2'',' 'B'',' 400);  ','',''),
('  ','','','','','',''),
('SELECT name','','','','','',''),
('       SUM(CASE WHEN parameter = 'A' THEN value ELSE 0 END) AS A','','','','','',''),
('       SUM(CASE WHEN parameter = 'B' THEN value ELSE 0 END) AS B','','','','','',''),
('  FROM Sample','','','','','',''),
('  GROUP BY name','','','','','',''),
('  ORDER BY name ASC;','','','','','',''),
('-- 9. Напишите запрос',' который выведет ID клиента',' его имя',' а также номер','','',''),
('-- первой выпущенной карты. Если в один день выпущено несколько карт',' то вывести','','','','',''),
('-- ту',' у которой ID меньше.','','','','',''),
('CREATE TABLE CLIENTS (client_id INTEGER',' client_name VARCHAR(100));','','','','',''),
('    INSERT INTO CLIENTS (client_id',' client_name) VALUES (1',' 'Иван');','','','',''),
('    INSERT INTO CLIENTS (client_id',' client_name) VALUES (2',' 'Семён');','','','',''),
('CREATE TABLE CCARDS (card_id INTEGER',' client_id INTEGER',' issue_date DATE',' card_num VARCHAR(100));','','',''),
('    INSERT INTO CCARDS (card_id',' client_id',' issue_date',' card_num) ','','',''),
('    			VALUES (1010',' 1',' (TO_DATE('01.08.2018'',' 'DD.MM.YYYY'))',' '*4565');','',''),
('    INSERT INTO CCARDS (card_id',' client_id',' issue_date',' card_num) ','','',''),
('    			VALUES (1011',' 1',' (TO_DATE('01.07.2019'',' 'DD.MM.YYYY'))',' '*4587');','',''),
('    INSERT INTO CCARDS (card_id',' client_id',' issue_date',' card_num) ','','',''),
('    			VALUES (3032',' 2',' (TO_DATE('01.08.2023'',' 'DD.MM.YYYY'))',' '*1257');','',''),
('    INSERT INTO CCARDS (card_id',' client_id',' issue_date',' card_num) ','','',''),
('    			VALUES (2082',' 2',' (TO_DATE('01.08.2023'',' 'DD.MM.YYYY'))',' '*2048');                ','',''),
('WITH CardsClients AS (','','','','','',''),
('  SELECT c1.client_id',' ','','','','',''),
('	 c1.client_name',' ','','','','',''),
('         MIN(c2.card_id) AS first_card_id','','','','','',''),
('    FROM CLIENTS c1 INNER JOIN CCARDS c2 ','','','','','',''),
('      ON c1.client_id = c2.client_id','','','','','',''),
('    GROUP BY c1.client_id',' c1.client_name','','','','',''),
('    ORDER BY client_id','','','','','',''),
('    )','','','','','',''),
('    ','','','','','',''),
('SELECT cc1.client_id',' cc1.client_name',' cc2.card_num','','','',''),
('  FROM CardsClients cc1 INNER JOIN CCARDS cc2','','','','','',''),
('    ON cc1.first_card_id = cc2.card_id;','','','','','',''),
('-- 10. Написать запрос',' который получает количество удержанных пользователей','','','','',''),
('--     в месяц. Данный параметр определяется как количество пользователей',' которые','','','','',''),
('--     авторизовались в системе и в этом (отчетном)',' и в предыдущем месяце.','','','','',''),
('CREATE TABLE LOGINS (user_id INTEGER',' log_date DATE);','','','','',''),
('    INSERT INTO LOGINS (user_id',' log_date) VALUES (1',' '2022-07-01');','','','',''),
('    INSERT INTO LOGINS (user_id',' log_date) VALUES (2',' '2022-07-02');','','','',''),
('    INSERT INTO LOGINS (user_id',' log_date) VALUES (3',' '2022-07-02');','','','',''),
('    INSERT INTO LOGINS (user_id',' log_date) VALUES (1',' '2022-07-02');','','','',''),
('    INSERT INTO LOGINS (user_id',' log_date) VALUES (2',' '2022-10-04');','','','',''),
('    INSERT INTO LOGINS (user_id',' log_date) VALUES (1',' '2022-08-01');','','','',''),
('    INSERT INTO LOGINS (user_id',' log_date) VALUES (2',' '2022-08-02');','','','',''),
('    INSERT INTO LOGINS (user_id',' log_date) VALUES (3',' '2022-08-02');','','','',''),
('    INSERT INTO LOGINS (user_id',' log_date) VALUES (1',' '2022-08-02');','','','',''),
('    INSERT INTO LOGINS (user_id',' log_date) VALUES (2',' '2022-11-04');','','','',''),
('SELECT DATE_TRUNC('month'',' log1.log_date) AS month',' ','','','',''),
('       COUNT(DISTINCT log1.user_id) AS unique_retained_users ','','','','','',''),
('  FROM LOGINS log1 INNER JOIN LOGINS log2 ','','','','','',''),
('    ON log1.user_id = log2.user_id ','','','','','',''),
('  WHERE DATE_TRUNC('month'',' log1.log_date) = ','','','','',''),
('    DATE_TRUNC('month'',' log2.log_date) + interval '1 month'','','','','',''),
('  GROUP BY DATE_TRUNC('month'',' log1.log_date);','','','','','');